-- ============================================================
-- HOTEL BOOKING SYSTEM — COMPLETE DATABASE SCRIPT
-- ============================================================
-- Tech: MySQL
-- Usage: Copy-paste this ENTIRE script into MySQL Workbench
--        and run it in one go (Ctrl+Shift+Enter)
-- ============================================================


-- ============================================================
-- STEP 1: CREATE DATABASE
-- ============================================================

DROP DATABASE IF EXISTS HotelBookingDB;
CREATE DATABASE HotelBookingDB;
USE HotelBookingDB;


-- ============================================================
-- STEP 2: CREATE TABLES (in order of dependencies)
-- ============================================================

-- TABLE 1: Users
-- Stores all registered users (customers + admins)
CREATE TABLE Users (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL DEFAULT 'User',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- TABLE 2: Hotels
-- Stores hotel information that users browse
CREATE TABLE Hotels (
    HotelId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Location VARCHAR(150) NOT NULL,
    Description TEXT NULL
);

-- TABLE 3: Amenities
-- Reusable amenity names shared across rooms
CREATE TABLE Amenities (
    AmenityId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

-- TABLE 4: Rooms
-- Each room belongs to a hotel
CREATE TABLE Rooms (
    RoomId INT AUTO_INCREMENT PRIMARY KEY,
    HotelId INT NOT NULL,
    RoomType VARCHAR(100) NOT NULL,
    PricePerNight DECIMAL(10,2) NOT NULL,
    Capacity INT NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (HotelId) REFERENCES Hotels(HotelId) ON DELETE CASCADE
);

-- TABLE 5: RoomAmenities (Junction / Mapping Table)
-- Many-to-Many: which room has which amenities
CREATE TABLE RoomAmenities (
    RoomId INT NOT NULL,
    AmenityId INT NOT NULL,
    PRIMARY KEY (RoomId, AmenityId),
    FOREIGN KEY (RoomId) REFERENCES Rooms(RoomId) ON DELETE CASCADE,
    FOREIGN KEY (AmenityId) REFERENCES Amenities(AmenityId) ON DELETE CASCADE
);

-- TABLE 6: Coupons
-- Discount codes that users can apply during booking
CREATE TABLE Coupons (
    CouponId INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    DiscountPercentage DECIMAL(5,2) NOT NULL,
    ExpiryDate DATE NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE
);

-- TABLE 7: Bookings (Core Table)
-- Every booking gets a row here
CREATE TABLE Bookings (
    BookingId INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    RoomId INT NOT NULL,
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL,
    TotalAmount DECIMAL(10,2) NOT NULL,
    CouponId INT NULL,
    DiscountAmount DECIMAL(10,2) DEFAULT 0,
    ReservationNumber VARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(UserId),
    FOREIGN KEY (RoomId) REFERENCES Rooms(RoomId),
    FOREIGN KEY (CouponId) REFERENCES Coupons(CouponId)
);


-- ============================================================
-- STEP 3: INSERT SEED DATA
-- ============================================================

-- ----- USERS -----
-- Admin password: Admin@123 (BCrypt hash — generated by backend on first register)
-- For testing, we insert a raw placeholder. The real hash is generated by ASP.NET BCrypt.
-- You should register the admin via API. This is just a fallback.
INSERT INTO Users (Name, Email, PasswordHash, Role) VALUES
('Admin', 'admin@stayease.com', '$2a$11$placeholder.admin.hash.here', 'Admin');

-- Test user password: User@123
INSERT INTO Users (Name, Email, PasswordHash, Role) VALUES
('Vaibhav', 'vaibhav@mail.com', '$2a$11$placeholder.user.hash.here', 'User'),
('Rahul', 'rahul@mail.com', '$2a$11$placeholder.user.hash.here', 'User');


-- ----- HOTELS (4 hotels) -----
INSERT INTO Hotels (Name, Location, Description) VALUES
('Taj Palace', 'Delhi', 'A luxury 5-star hotel with world-class amenities, spa, and fine dining. Located in the heart of New Delhi near India Gate.'),
('Marriott Mumbai', 'Mumbai', 'Premium business hotel in the heart of Mumbai with stunning sea views. Perfect for both business and leisure travelers.'),
('Grand Hyatt', 'Pune', 'Modern hotel with state-of-the-art conference facilities, rooftop pool, and award-winning restaurants.'),
('Oberoi Palace', 'Jaipur', 'Heritage hotel with royal Rajasthani architecture, lush gardens, and a world-class spa experience.');


-- ----- AMENITIES (8 amenities) -----
INSERT INTO Amenities (Name) VALUES
('WiFi'),        -- AmenityId = 1
('AC'),          -- AmenityId = 2
('TV'),          -- AmenityId = 3
('Pool'),        -- AmenityId = 4
('Gym'),         -- AmenityId = 5
('Parking'),     -- AmenityId = 6
('Restaurant'),  -- AmenityId = 7
('Mini Bar');    -- AmenityId = 8


-- ----- ROOMS (9 rooms across 4 hotels) -----

-- Hotel 1: Taj Palace (Delhi) — 3 rooms
INSERT INTO Rooms (HotelId, RoomType, PricePerNight, Capacity) VALUES
(1, 'Deluxe Room', 2500.00, 2),       -- RoomId = 1
(1, 'Suite', 5000.00, 4),             -- RoomId = 2
(1, 'Standard Room', 1200.00, 2);     -- RoomId = 3

-- Hotel 2: Marriott Mumbai — 2 rooms
INSERT INTO Rooms (HotelId, RoomType, PricePerNight, Capacity) VALUES
(2, 'Deluxe Room', 3000.00, 2),       -- RoomId = 4
(2, 'Standard Room', 1500.00, 2);     -- RoomId = 5

-- Hotel 3: Grand Hyatt (Pune) — 2 rooms
INSERT INTO Rooms (HotelId, RoomType, PricePerNight, Capacity) VALUES
(3, 'Suite', 4500.00, 4),             -- RoomId = 6
(3, 'Deluxe Room', 2200.00, 2);       -- RoomId = 7

-- Hotel 4: Oberoi Palace (Jaipur) — 2 rooms
INSERT INTO Rooms (HotelId, RoomType, PricePerNight, Capacity) VALUES
(4, 'Royal Suite', 8000.00, 4),       -- RoomId = 8
(4, 'Heritage Room', 3500.00, 2);     -- RoomId = 9


-- ----- ROOM AMENITIES (mapping rooms to amenities) -----

-- Room 1: Taj Deluxe → WiFi, AC, TV, Mini Bar
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(1, 1), (1, 2), (1, 3), (1, 8);

-- Room 2: Taj Suite → WiFi, AC, TV, Pool, Mini Bar
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(2, 1), (2, 2), (2, 3), (2, 4), (2, 8);

-- Room 3: Taj Standard → WiFi, AC
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(3, 1), (3, 2);

-- Room 4: Marriott Deluxe → WiFi, AC, TV, Gym
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(4, 1), (4, 2), (4, 3), (4, 5);

-- Room 5: Marriott Standard → WiFi, AC
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(5, 1), (5, 2);

-- Room 6: Hyatt Suite → WiFi, AC, TV, Pool, Gym
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(6, 1), (6, 2), (6, 3), (6, 4), (6, 5);

-- Room 7: Hyatt Deluxe → WiFi, AC, TV
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(7, 1), (7, 2), (7, 3);

-- Room 8: Oberoi Royal Suite → ALL amenities
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8);

-- Room 9: Oberoi Heritage → WiFi, AC, TV, Restaurant
INSERT INTO RoomAmenities (RoomId, AmenityId) VALUES
(9, 1), (9, 2), (9, 3), (9, 7);


-- ----- COUPONS (3 discount codes) -----
INSERT INTO Coupons (Code, DiscountPercentage, ExpiryDate, IsActive) VALUES
('SAVE20', 20.00, '2026-12-31', TRUE),
('SUMMER15', 15.00, '2026-06-30', TRUE),
('WELCOME10', 10.00, '2026-09-30', TRUE);


-- ----- SAMPLE BOOKINGS (2 test bookings) -----
INSERT INTO Bookings (UserId, RoomId, CheckInDate, CheckOutDate, TotalAmount, CouponId, DiscountAmount, ReservationNumber) VALUES
(2, 1, '2026-04-15', '2026-04-17', 4000.00, 1, 1000.00, 'RES-ABCD1234'),
(2, 4, '2026-05-01', '2026-05-03', 6000.00, NULL, 0.00, 'RES-EFGH5678');


-- ============================================================
-- STEP 4: VERIFY — Run these SELECT queries to confirm
-- ============================================================

SELECT '--- USERS ---' AS '';
SELECT UserId, Name, Email, Role FROM Users;

SELECT '--- HOTELS ---' AS '';
SELECT * FROM Hotels;

SELECT '--- AMENITIES ---' AS '';
SELECT * FROM Amenities;

SELECT '--- ROOMS ---' AS '';
SELECT r.RoomId, h.Name AS Hotel, r.RoomType, r.PricePerNight, r.Capacity
FROM Rooms r
JOIN Hotels h ON r.HotelId = h.HotelId;

SELECT '--- ROOM AMENITIES ---' AS '';
SELECT r.RoomId, r.RoomType, h.Name AS Hotel, GROUP_CONCAT(a.Name SEPARATOR ', ') AS Amenities
FROM Rooms r
JOIN Hotels h ON r.HotelId = h.HotelId
JOIN RoomAmenities ra ON r.RoomId = ra.RoomId
JOIN Amenities a ON ra.AmenityId = a.AmenityId
GROUP BY r.RoomId, r.RoomType, h.Name;

SELECT '--- COUPONS ---' AS '';
SELECT * FROM Coupons;

SELECT '--- BOOKINGS ---' AS '';
SELECT b.BookingId, u.Name AS User, h.Name AS Hotel, r.RoomType,
       b.CheckInDate, b.CheckOutDate, b.TotalAmount, b.DiscountAmount, b.ReservationNumber
FROM Bookings b
JOIN Users u ON b.UserId = u.UserId
JOIN Rooms r ON b.RoomId = r.RoomId
JOIN Hotels h ON r.HotelId = h.HotelId;


-- ============================================================
-- DONE! Your database is ready.
-- ============================================================
-- Tables created:  7
-- Hotels seeded:   4
-- Amenities:       8
-- Rooms:           9
-- Room-Amenity:    30 mappings
-- Coupons:         3
-- Sample bookings: 2
-- Users:           3 (1 admin + 2 test users)
-- ============================================================
